version: '3'

services:
  app:
    command: "_build/dev/rel/ranciobot/bin/ranciobot foreground"
    image: ranciobot:1.0.0
    build:
      context: .
    working_dir: /opt/app
    volumes:
      - ./:/opt/app
    env_file: .env
